# version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hellodb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./hellodb.sql:/docker-entrypoint-initdb.d/hellodb.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: thepouriya/uniproject-backend:latest
    ports:
      - "9001:9001"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_USER: myuser
      DB_PASS: mypass
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: hellodb

  frontend:
    image: thepouriya/uniproject-frontend:latest
    ports:
      - "9000:9000"

volumes:
  mysql_data:
