version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hellodb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - ./hellodb.sql:/docker-entrypoint-initdb.d/hellodb.sql

  backend:
    build: ../backend
    ports:
      - "9001:9001"
    depends_on:
      - mysql
    environment:
      DB_USER: myuser
      DB_PASS: mypass
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: hellodb

  frontend:
    build: ../frontend
    ports:
      - "9000:9000"